config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'auctions#index'
  resources :auctions, only: [:new, :show, :index, :create] do
    resources :bids, only: [:create, :destroy]
    resources :publishings, only: :create
    resources :tracks, only: [:create, :destroy]
  end

  resources :users, only:[:new, :create, :show] do
    resources :tracks, only: [:index]
  end
  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :user
  has_many :tracks, dependent: :destroy
  has_many :bids, dependent: :destroy
  validates :title, presence: true
  validates :details, presence: true
  validates :ends_on, presence: true
  validates :reserve_price, presence: true
  validates :current_price, presence:true

  include AASM
    aasm whiny_transitions: false do
    state :draft, initial: true
    state :published
    state :reserve_met
    state :reserve_not_met
    state :won
    state :cancelled


    event :publish do
      transitions from: :draft, to: :published
    end

    event :reserve_meet do
      transitions from: :published, to: :reserve_met
    end

    event :reserve_not_meet do
      transitions from: :published, to: :reserve_not_met
    end

    event :win do
      transitions from: :reserve_met, to: :won
    end

    event :cancel do
      transitions from: [:published, :reserve_met, :reserve_not_met, :won], to: :cancelled
    end

    event :relaunch do
      transitions from: :cancelled, to: :draft
    end

  end

  def track_by?(user)
    tracks.exists?(user: user)
  end

  def track_for(user)
    tracks.find_by(user: user)
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :get_auction, only:[:show]
  before_action :authenticate_user!, except: [:show, :index]


  def index
    @auctions = Auction.all
  end

  def new
    @auction = Auction.new
  end

  def create
    # post_params = params.require(:post).permit([:title, :body, :category_id])
    @auction = Auction.new (auction_params)
    @auction.user = current_user
    if @auction.save
      flash[:notice] = "A New Auction Created Successfully!"
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  def show
    @bid = Bid.new
    @current_price = @auction.current_price
    @reserve_price = @auction.reserve_price
  end

  private
  def get_auction
    @auction = Auction.find(params[:id])
  end

  def auction_params
    params.require(:auction).permit([:title, :details, :ends_on, :reserve_price])
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/index.html.erb
<h1>All Current Auction </h1>
<ul>
  <% @auctions.each do |auction| %>
    <h3><li><%= auction.title %></li></h3>
    <span> <%= link_to 'View this auction', auction_path(auction.id)%></span>
  <% end %>
</ul>

app/views/auctions/new.html.erb
<h1>Auction New</h1>

<h1>Create Your Auction</h1>
<%= form_for @auction do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class:"form-control" %>
</div>
<div class="form-group">
  <%= f.label :details %>
  <%= f.text_area :details, rows:"8", class:"form-control"%>
</div>
<div class="form-group">
  <%= f.label :ends_on %>
  <%= f.date_field :ends_on, class:"form-control"%>
</div>
<div class="form-group">
  <%= f.label :reserve_price %>
  <%= f.text_field :reserve_price, class:"form-control"%>
</div>
<div class="form-group">
  <%= f.submit "Create", class:"btn btn-primary"%>
</div>
<% end %>

app/views/auctions/show.html.erb
<h1>Auction Show</h1>

<div class="col-md-8">
  <h3>Auction Title: <%= @auction.title %></h3>
  <p>Owner: <%= @auction.user.first_name.capitalize %></p>
  <p><%= @auction.details %></p>
  <% if @auction.may_publish? && @auction.user == current_user%>

  <%= link_to 'Publish', auction_publishings_path(@auction), method: :post %>
  <% end %>

  <% if user_signed_in? && (can? :track, @auction)%>
    <% if !@auction.track_by?(current_user) %>
      <%= link_to fa_icon("eye"), auction_tracks_path(@auction), method: :post%>
    <% else %>
      <%= link_to fa_icon("eye-slash"),  auction_tracks_path(@auction, @auction.track_for(current_user)), method: :delete %>
    <% end %>
    <span><%= pluralize(@auction.tracks.count, 'track') %></span>
  <% end %>

  <%= form_for [@auction, @bid] do |f| %>
    <%= f.text_field :price, placeholder: "Bid Price" %>
    <%= f.submit class: "btn" %>
  <% end %>


  <h4>Previous bids</h4>
  <ul>
    <% @auction.bids.each do |b| %>
    <li>
      <span>$<%= b.price %> at <%= b.created_at.strftime("%b %d %Y") %></span>
      &nbsp
      <span><i class="fa fa-user-o" aria-hidden="true"></i>
        <%= b.user.first_name.capitalize %> <%= b.user.last_name.capitalize %>
      </span>
    </li>
    <%= link_to 'Delete', auction_bid_path(@auction, b), class: "btn btn-danger", method: :delete, data:{confirm: 'Are you sure?'} %>
    <% end %>
  </ul>

</div>

<div class="col-md-4">
  <h3>Current Price: $<%= @current_price%></h3>
  <%if @current_price >= @reserve_price %>
    <p>Reserve Price Met</p>
  <% else %>
    <p>Reserve Price Not Met</p>
  <% end %>
</div>