config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'auctions#index'
  resources :auctions, only: [:new, :show, :index, :create] do
    resources :bids, only: [:create, :destroy]
    resources :publishings, only: :create
    resources :tracks, only: [:create, :destroy]
  end

  resources :users, only:[:new, :create, :show] do
    resources :tracks, only: [:index]
  end
  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/user.rb
class User < ApplicationRecord
has_many :auctions, dependent: :destroy
has_many :bids, dependent: :destroy
has_many :tracks, dependent: :destroy
has_many :track_auctions, through: :tracks, source: :auction

has_secure_password

validates :first_name, presence: true
validates :last_name, presence: true
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
validates :email, presence: true,
                  uniqueness: { case_sensitive: false },
                  format: VALID_EMAIL_REGEX

before_validation :downcase_email

private
def downcase_email
  self.email.downcase! if email.present?
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :get_user, only:[:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing in"
      redirect_to root_path
    else
      flash[:alert] = "Invalid user info!"
      render :new
    end
  end

  def show
  end
  private
    def get_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<%= @user.errors.full_messages.join(', ') %>
<div class="row" id="signup">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3>Registration</h3>
              </div>
              <div class="panel-body">
                <%= form_for @user do |f| %>
                  <hr>
                  <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                      <div class="form-group">
                        <%= f.text_field :first_name, class:'form-control input-md', placeholder: "First Name" %>
                      </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                      <div class="form-group">
                        <%= f.text_field :last_name, class:'form-control input-md', placeholder: "Last Name" %>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.email_field :email, class:'form-control input-md', placeholder: "Email Address" %>
                  </div>

                  <div class="form-group">
                    <%= f.password_field :password, class:'form-control input-md', placeholder: "Password" %>
                  </div>

                  <div class="form-group">
                    <%= f.password_field :password_confirmation, class:'form-control input-md', placeholder: "Password Confirmation" %>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-xs-12 col-md-6"><input type="submit" value="Create my account" class="btn btn-primary btn-block btn-md input-md" tabindex="7"></div>
                  </div>
                <% end %>
              </div>
            </div>

      	  </div>
</div>

app/views/users/show.html.erb
<h1>All Auction <%= @user.first_name.capitalize %> has made bids on them</h1>
<ul>
  <% @user.bids.each do |b| %>
    <h3><li><%= b.auction.title %></li></h3>
    <span><%= link_to "See Details", auction_path(b.auction) %></span>
  <% end %>
</ul>